### ISSUE TITLE
Why is there only one node? Where is the node for loading the model?

### ISSUE THREAD

**Issue by wibur0620** [ExponentialML/ComfyUI_Native_DynamiCrafter#3]
![屏幕截图 2024-03-22 004355](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/assets/131615326/e3b278f5-1253-4e10-822b-3ead816dfe8e)

**Comment by wibur0620** [comment]
Moreover, the name chosen seems quite arbitrary, which can be unsettling for those with OCD
![屏幕截图 2024-03-22 004644](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/assets/131615326/0008b9ac-3ac5-41b8-adc6-4b2f0f675bfa)

**Comment by ExponentialML** [comment]
Hi. The node can be found as "Load a DynamiCrafter Checkpoint". I will add a specific category for the nodes to help sort them.

**Comment by wibur0620** [comment]
> Hi. The node can be found as "Load a DynamiCrafter Checkpoint". I will add a specific category for the nodes to help sort them.你好。该节点可以作为“加载 DynamiCrafter 检查点”找到。我将为节点添加一个特定的类别，以帮助对它们进行排序。

In which category is this node located? I couldn't find it.

**Comment by wibur0620** [comment]
![image](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/assets/131615326/c4252f7f-9108-43e5-975a-5eed5f7c05b9)

**Comment by ExponentialML** [comment]
Please pull the latest update. You should now see it under the drop down menu as "Native_DynamiCrafter".

**Comment by wibur0620** [comment]
[comfyui.log](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/files/14704805/comfyui.log)

**Comment by ExponentialML** [comment]
![image](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/assets/59846140/913f6d33-d18c-4864-b0de-810b8018dd3c)

**Comment by wibur0620** [comment]
It turns out I hadn't created the 'dynamicrafter_models' folder for it yet. It's sorted now, thank you
![image](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/assets/131615326/dbb079d2-9aac-4408-943e-319cc2112c4d)

**Comment by jinnaluo0** [comment]
create a folder:ComfyUI_windows_portable\ComfyUI\models\dynamicrafter_models
then restart the comfyui server

by the way,where can I download DynamiCrafter.safetensors?
