### ISSUE TITLE
DynamiCrafterLoader 时发生错误：  DynamiCrafterBase "对象没有 "supported_inference_dtypes "属性

### ISSUE THREAD

**Issue by louis75691710** [ExponentialML/ComfyUI_Native_DynamiCrafter#8]
已解决

**Comment by louis75691710** [comment]
![微信截图_20240328141121](https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter/assets/69236216/46714124-ef40-448a-b855-ae7100d227a9)
请问这是什么情况，帮忙看看。谢谢

**Comment by danton267** [comment]
@louis75691710  how did you solve it?

**Comment by erjihaoshi** [comment]
> 已解决
the same issue as yours ,can you  tell me how to fix it
